-- sql/rollback-037.sql - KEMBALIKAN kebijakan RLS ke keadaan sebelum migrasi 037 (salinan 2026-10-08).
-- Hanya dipakai bila 037 ternyata mengubah hak akses. Jalankan utuh di SQL Editor Supabase.

begin;
drop policy if exists bpm_baca on public.brand_pic_mappings;
drop policy if exists bpm_tulis on public.brand_pic_mappings;
drop policy if exists bpm_tulis_tambah on public.brand_pic_mappings;
drop policy if exists bpm_tulis_ubah on public.brand_pic_mappings;
drop policy if exists bpm_tulis_hapus on public.brand_pic_mappings;
drop policy if exists drte_baca on public.daily_report_team_entries;
drop policy if exists drte_tulis on public.daily_report_team_entries;
drop policy if exists drte_tulis_tambah on public.daily_report_team_entries;
drop policy if exists drte_tulis_ubah on public.daily_report_team_entries;
drop policy if exists drte_tulis_hapus on public.daily_report_team_entries;
drop policy if exists division_ivp_mappings_baca on public.division_ivp_mappings;
drop policy if exists division_ivp_mappings_tulis on public.division_ivp_mappings;
drop policy if exists division_ivp_mappings_tulis_tambah on public.division_ivp_mappings;
drop policy if exists division_ivp_mappings_tulis_ubah on public.division_ivp_mappings;
drop policy if exists division_ivp_mappings_tulis_hapus on public.division_ivp_mappings;
drop policy if exists division_supervisor_mappings_baca on public.division_supervisor_mappings;
drop policy if exists division_supervisor_mappings_tulis on public.division_supervisor_mappings;
drop policy if exists division_supervisor_mappings_tulis_tambah on public.division_supervisor_mappings;
drop policy if exists division_supervisor_mappings_tulis_ubah on public.division_supervisor_mappings;
drop policy if exists division_supervisor_mappings_tulis_hapus on public.division_supervisor_mappings;
drop policy if exists fr_baca on public.form_reviews;
drop policy if exists fr_tulis on public.form_reviews;
drop policy if exists fr_tulis_tambah on public.form_reviews;
drop policy if exists fr_tulis_ubah on public.form_reviews;
drop policy if exists fr_tulis_hapus on public.form_reviews;
drop policy if exists iss_baca on public.incentive_scheme_settings;
drop policy if exists iss_tulis on public.incentive_scheme_settings;
drop policy if exists iss_tulis_tambah on public.incentive_scheme_settings;
drop policy if exists iss_tulis_ubah on public.incentive_scheme_settings;
drop policy if exists iss_tulis_hapus on public.incentive_scheme_settings;
drop policy if exists kgs_baca on public.kpi_global_settings;
drop policy if exists kgs_tulis on public.kpi_global_settings;
drop policy if exists kgs_tulis_tambah on public.kpi_global_settings;
drop policy if exists kgs_tulis_ubah on public.kpi_global_settings;
drop policy if exists kgs_tulis_hapus on public.kpi_global_settings;
drop policy if exists kps_baca on public.kpi_period_snapshots;
drop policy if exists kps_tulis on public.kpi_period_snapshots;
drop policy if exists kps_tulis_tambah on public.kpi_period_snapshots;
drop policy if exists kps_tulis_ubah on public.kpi_period_snapshots;
drop policy if exists kps_tulis_hapus on public.kpi_period_snapshots;
drop policy if exists pimpinan_baca on public.lc_answers;
drop policy if exists lcj_milik on public.lc_answers;
drop policy if exists lcj_milik_tambah on public.lc_answers;
drop policy if exists lcj_milik_ubah on public.lc_answers;
drop policy if exists lcj_milik_hapus on public.lc_answers;
drop policy if exists lcm_baca on public.lc_materials;
drop policy if exists lcm_tulis on public.lc_materials;
drop policy if exists lcm_tulis_tambah on public.lc_materials;
drop policy if exists lcm_tulis_ubah on public.lc_materials;
drop policy if exists lcm_tulis_hapus on public.lc_materials;
drop policy if exists lcq_baca on public.lc_questions;
drop policy if exists lcq_tulis on public.lc_questions;
drop policy if exists lcq_tulis_tambah on public.lc_questions;
drop policy if exists lcq_tulis_ubah on public.lc_questions;
drop policy if exists lcq_tulis_hapus on public.lc_questions;
drop policy if exists pimpinan_baca on public.lc_quiz_attempts;
drop policy if exists lca_milik on public.lc_quiz_attempts;
drop policy if exists lca_milik_tambah on public.lc_quiz_attempts;
drop policy if exists lca_milik_ubah on public.lc_quiz_attempts;
drop policy if exists lca_milik_hapus on public.lc_quiz_attempts;
drop policy if exists lcs_baca on public.lc_quiz_sessions;
drop policy if exists lcs_tulis on public.lc_quiz_sessions;
drop policy if exists lcs_tulis_tambah on public.lc_quiz_sessions;
drop policy if exists lcs_tulis_ubah on public.lc_quiz_sessions;
drop policy if exists lcs_tulis_hapus on public.lc_quiz_sessions;
drop policy if exists os_baca on public.overdue_settings;
drop policy if exists os_tulis on public.overdue_settings;
drop policy if exists os_tulis_tambah on public.overdue_settings;
drop policy if exists os_tulis_ubah on public.overdue_settings;
drop policy if exists os_tulis_hapus on public.overdue_settings;
drop policy if exists ph_baca on public.picket_holidays;
drop policy if exists ph_tulis on public.picket_holidays;
drop policy if exists ph_tulis_tambah on public.picket_holidays;
drop policy if exists ph_tulis_ubah on public.picket_holidays;
drop policy if exists ph_tulis_hapus on public.picket_holidays;
drop policy if exists ptm_baca on public.product_team_map;
drop policy if exists ptm_tulis on public.product_team_map;
drop policy if exists ptm_tulis_tambah on public.product_team_map;
drop policy if exists ptm_tulis_ubah on public.product_team_map;
drop policy if exists ptm_tulis_hapus on public.product_team_map;
drop policy if exists psl_select on public.project_source_links;
drop policy if exists psl_write on public.project_source_links;
drop policy if exists psl_write_tambah on public.project_source_links;
drop policy if exists psl_write_ubah on public.project_source_links;
drop policy if exists psl_write_hapus on public.project_source_links;
drop policy if exists projects_select on public.projects;
drop policy if exists projects_write on public.projects;
drop policy if exists projects_write_tambah on public.projects;
drop policy if exists projects_write_ubah on public.projects;
drop policy if exists projects_write_hapus on public.projects;
drop policy if exists tm_baca on public.team_members;
drop policy if exists tm_tulis on public.team_members;
drop policy if exists tm_tulis_tambah on public.team_members;
drop policy if exists tm_tulis_ubah on public.team_members;
drop policy if exists tm_tulis_hapus on public.team_members;
drop policy if exists user_supervisor_mappings_baca on public.user_supervisor_mappings;
drop policy if exists user_supervisor_mappings_tulis on public.user_supervisor_mappings;
drop policy if exists user_supervisor_mappings_tulis_tambah on public.user_supervisor_mappings;
drop policy if exists user_supervisor_mappings_tulis_ubah on public.user_supervisor_mappings;
drop policy if exists user_supervisor_mappings_tulis_hapus on public.user_supervisor_mappings;

create policy bpm_baca on public.brand_pic_mappings as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy bpm_tulis on public.brand_pic_mappings as permissive for ALL to anon, authenticated using ((jwt_claim('user_role'::text) = ANY (ARRAY['admin'::text, 'superadmin'::text]))) with check ((jwt_claim('user_role'::text) = ANY (ARRAY['admin'::text, 'superadmin'::text])));
create policy drte_baca on public.daily_report_team_entries as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy drte_tulis on public.daily_report_team_entries as permissive for ALL to anon, authenticated using (((entered_by = jwt_claim('username'::text)) OR admin_atau_full_access())) with check (((entered_by = jwt_claim('username'::text)) OR admin_atau_full_access()));
create policy division_ivp_mappings_baca on public.division_ivp_mappings as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy division_ivp_mappings_tulis on public.division_ivp_mappings as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy division_supervisor_mappings_baca on public.division_supervisor_mappings as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy division_supervisor_mappings_tulis on public.division_supervisor_mappings as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy fr_baca on public.form_reviews as permissive for SELECT to anon, authenticated using ((is_progress_admin() OR ( SELECT pimpinan_lihat_semua() AS pimpinan_lihat_semua) OR (guest_username = jwt_claim('username'::text)) OR (sales_name = jwt_full_name())));
create policy fr_tulis on public.form_reviews as permissive for ALL to anon, authenticated using ((admin_atau_full_access() OR (guest_username = jwt_claim('username'::text)) OR (assigned_to = jwt_claim('username'::text)))) with check ((admin_atau_full_access() OR (guest_username = jwt_claim('username'::text)) OR (assigned_to = jwt_claim('username'::text))));
create policy iss_baca on public.incentive_scheme_settings as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy iss_tulis on public.incentive_scheme_settings as permissive for ALL to anon, authenticated using (akses_insentif_penuh()) with check (akses_insentif_penuh());
create policy kgs_baca on public.kpi_global_settings as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy kgs_tulis on public.kpi_global_settings as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy kps_baca on public.kpi_period_snapshots as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy kps_tulis on public.kpi_period_snapshots as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy lcj_milik on public.lc_answers as permissive for ALL to anon, authenticated using ((((user_id)::text = jwt_claim('sub'::text)) OR admin_atau_full_access())) with check ((((user_id)::text = jwt_claim('sub'::text)) OR admin_atau_full_access()));
create policy pimpinan_baca on public.lc_answers as permissive for SELECT to public using (( SELECT pimpinan_lihat_semua() AS pimpinan_lihat_semua));
create policy lcm_baca on public.lc_materials as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy lcm_tulis on public.lc_materials as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy lcq_baca on public.lc_questions as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy lcq_tulis on public.lc_questions as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy lca_milik on public.lc_quiz_attempts as permissive for ALL to anon, authenticated using ((((user_id)::text = jwt_claim('sub'::text)) OR admin_atau_full_access())) with check ((((user_id)::text = jwt_claim('sub'::text)) OR admin_atau_full_access()));
create policy pimpinan_baca on public.lc_quiz_attempts as permissive for SELECT to public using (( SELECT pimpinan_lihat_semua() AS pimpinan_lihat_semua));
create policy lcs_baca on public.lc_quiz_sessions as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy lcs_tulis on public.lc_quiz_sessions as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy os_baca on public.overdue_settings as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy os_tulis on public.overdue_settings as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy ph_baca on public.picket_holidays as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy ph_tulis on public.picket_holidays as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy ptm_baca on public.product_team_map as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy ptm_tulis on public.product_team_map as permissive for ALL to anon, authenticated using ((jwt_claim('user_role'::text) = ANY (ARRAY['admin'::text, 'superadmin'::text]))) with check ((jwt_claim('user_role'::text) = ANY (ARRAY['admin'::text, 'superadmin'::text])));
create policy psl_select on public.project_source_links as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy psl_write on public.project_source_links as permissive for ALL to anon, authenticated using ((jwt_claim('user_role'::text) = ANY (ARRAY['admin'::text, 'superadmin'::text]))) with check ((jwt_claim('user_role'::text) = ANY (ARRAY['admin'::text, 'superadmin'::text])));
create policy projects_select on public.projects as permissive for SELECT to anon, authenticated using (boleh_lihat_baris(NULL::uuid, sales_name, sales_division, NULL::text));
create policy projects_write on public.projects as permissive for ALL to anon, authenticated using ((jwt_claim('user_role'::text) = ANY (ARRAY['admin'::text, 'superadmin'::text]))) with check ((jwt_claim('user_role'::text) = ANY (ARRAY['admin'::text, 'superadmin'::text])));
create policy tm_baca on public.team_members as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy tm_tulis on public.team_members as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
create policy user_supervisor_mappings_baca on public.user_supervisor_mappings as permissive for SELECT to anon, authenticated using ((jwt_claim('sub'::text) <> ''::text));
create policy user_supervisor_mappings_tulis on public.user_supervisor_mappings as permissive for ALL to anon, authenticated using (admin_atau_full_access()) with check (admin_atau_full_access());
commit;
